/-
Copyright (c) 2026 LemmaFeld Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LemmaFeld Contributors
-/
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.CategoryTheory.Simple
import Mathlib.CategoryTheory.Abelian.Basic
import Mathlib.Algebra.Homology.ShortComplex.ShortExact
import Mathlib.Order.JordanHolder
import LemmaFeld.CategoryTheory.TensorCategories.Chapter1.JordanHolder

/-!
# Chapter 1, Section 1.5.8: Grothendieck Group

Formalizes Definition 1.5.8 (Grothendieck group Gr(C)) from Etingof et al.
"Tensor Categories" (AMS 2015), §1.5.

## §1.5.8 Definition

Book: "The Grothendieck group Gr(C) of C is the free abelian group generated by
isomorphism classes X_i of simple objects in C. To every object X in C we can
canonically associate its class [X] ∈ Gr(C) given by the formula
  [X] = ∑_i [X : X_i] X_i"

Key property: If 0 → X → Y → Z → 0 is exact, then [Y] = [X] + [Z].

## Mathlib Correspondence

| Book | Mathlib | Notes |
|------|---------|-------|
| Free abelian group | `FreeAbelianGroup α` | `Mathlib.GroupTheory.FreeAbelianGroup` |
| K₀ of monoid | `Algebra.GrothendieckGroup` | Different: localizes a monoid |
| JH multiplicity | — | Gap: no `JordanHolderLattice (Subobject X)` |

**Gap:** Full class map [X] requires Jordan-Hölder multiplicities for categories.
-/

noncomputable section

namespace LemmaFeld.TensorCategories.Chapter1

open CategoryTheory CategoryTheory.Limits

/-! ## Simple Objects Type -/

section SimpleObjectsType

variable (C : Type*) [Category C] [HasZeroMorphisms C]

/-- The type of simple objects in C (as a subtype). -/
def SimpleObject := { X : C // Simple X }

instance : CoeOut (SimpleObject C) C where coe := Subtype.val

/-- Two simple objects are isomorphic if their underlying objects are. -/
def SimpleObject.Isomorphic (X Y : SimpleObject C) : Prop := Nonempty (X.val ≅ Y.val)

/-- Isomorphism of simple objects is an equivalence relation. -/
lemma SimpleObject.isomorphic_equivalence : Equivalence (SimpleObject.Isomorphic C) where
  refl X := ⟨Iso.refl X.val⟩
  symm := fun ⟨i⟩ => ⟨i.symm⟩
  trans := fun ⟨i⟩ ⟨j⟩ => ⟨i.trans j⟩

/-- Setoid on simple objects by isomorphism. -/
def SimpleObject.setoid : Setoid (SimpleObject C) where
  r := SimpleObject.Isomorphic C
  iseqv := SimpleObject.isomorphic_equivalence C

/-- Isomorphism classes of simple objects. -/
def IsoClassSimple := Quotient (SimpleObject.setoid C)

end SimpleObjectsType

/-! ## Grothendieck Group Definition -/

section GrothendieckGroupDef

variable (C : Type*) [Category C] [HasZeroMorphisms C]

/-- The Grothendieck group Gr(C) is the free abelian group on isomorphism classes
of simple objects. Book Definition 1.5.8. -/
def GrothendieckGroup := FreeAbelianGroup (IsoClassSimple C)

instance : AddCommGroup (GrothendieckGroup C) :=
  inferInstanceAs (AddCommGroup (FreeAbelianGroup (IsoClassSimple C)))

/-- Inclusion of a simple object's class into the Grothendieck group. -/
def simpleClass (X : SimpleObject C) : GrothendieckGroup C :=
  FreeAbelianGroup.of (Quotient.mk (SimpleObject.setoid C) X)

end GrothendieckGroupDef

/-! ## Jordan-Hölder Multiplicity

The book defines [X] = ∑_i [X : X_i] X_i where [X : Y] is the Jordan-Hölder multiplicity.
**Gap:** This requires `JordanHolderLattice (Subobject X)` which mathlib lacks.
-/

section Multiplicity

variable {C : Type*} [Category C] [Abelian C]

/-- Axiomatized Jordan-Hölder multiplicity for abelian categories.
Book notation: [X : Y] = multiplicity of simple Y in X. -/
class HasMultiplicity (C : Type*) [Category C] [Abelian C] where
  multiplicity : (X : C) → (Y : C) → [Simple Y] → ℕ
  multiplicity_zero_of_isZero : ∀ (X : C), IsZero X → ∀ (Y : C) [Simple Y],
    multiplicity X Y = 0
  multiplicity_self : ∀ (Y : C) [Simple Y], multiplicity Y Y = 1
  multiplicity_add : ∀ (S : ShortComplex C), S.ShortExact → ∀ (Y : C) [Simple Y],
    multiplicity S.X₂ Y = multiplicity S.X₁ Y + multiplicity S.X₃ Y

variable [HasMultiplicity C]

/-- The multiplicity [X : Y] of simple Y in X. -/
abbrev mult (X Y : C) [Simple Y] : ℕ := HasMultiplicity.multiplicity X Y

end Multiplicity

/-! ## Object Class Data

For finite abelian categories, we can sum over finitely many simple classes.
-/

section ObjectClassData

variable (C : Type*) [Category C] [Abelian C] [HasMultiplicity C]

/-- Data needed to define the class map [_] : Ob(C) → Gr(C). -/
structure ObjectClassData where
  simples : Type*
  toObj : simples → C
  simple_inst : ∀ i : simples, Simple (toObj i)
  finite : Finite simples
  complete : ∀ Y : C, Simple Y → ∃ i : simples, Nonempty (Y ≅ toObj i)

end ObjectClassData

/-! ## Module Case

For modules, `JordanHolderLattice (Submodule R M)` exists in mathlib.
-/

section ModuleCase

variable {R : Type*} [Ring R] {M : Type*} [AddCommGroup M] [Module R M]

example : JordanHolderLattice (Submodule R M) := inferInstance

example (s₁ s₂ : CompositionSeries (Submodule R M))
    (hhead : s₁.head = s₂.head) (hlast : s₁.last = s₂.last) :
    s₁.length = s₂.length :=
  (CompositionSeries.jordan_holder s₁ s₂ hhead hlast).length_eq

end ModuleCase

/-! ## Properties

Note: Mathlib's `Algebra.GrothendieckGroup M` localizes a monoid at ⊤.
Our categorical Gr(C) uses simple object classes and JH multiplicities.
-/

section Properties

variable {C : Type*} [Category C] [Abelian C]

/-- Gr(C) is generated by classes of simple objects. -/
theorem grothendieckGroup_generated_by_simples :
    ∀ g : GrothendieckGroup C, ∃ (n : ℕ) (coeffs : Fin n → ℤ)
      (simples : Fin n → IsoClassSimple C),
      g = Finset.univ.sum fun i => coeffs i • FreeAbelianGroup.of (simples i) := by
  intro g; sorry

/-- Isomorphic simple objects define the same class in Gr(C). -/
theorem simpleClass_eq_of_iso {X Y : SimpleObject C} (h : X.val ≅ Y.val) :
    simpleClass C X = simpleClass C Y := by
  unfold simpleClass; congr 1; exact Quotient.sound ⟨h⟩

end Properties

end LemmaFeld.TensorCategories.Chapter1
