/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AF-Tests Project
-/
import LemmaFeld.GroupTheory.AF.Core.Generators
import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# The Group H = ⟨g₁, g₂, g₃⟩

This file defines the subgroup H generated by g₁, g₂, g₃.

## Main Definitions

* `H n k m` - The subgroup of Perm(Omega n k m) generated by {g₁, g₂, g₃}
* `H₆` - The base case H with n = k = m = 0, acting on Fin 6

## Main Results

* `g₁_mem_H`, `g₂_mem_H`, `g₃_mem_H` - Generators are in H
-/

/-- The group H = ⟨g₁, g₂, g₃⟩ as a subgroup of Perm(Omega n k m) -/
def H (n k m : ℕ) : Subgroup (Equiv.Perm (Omega n k m)) :=
  Subgroup.closure {g₁ n k m, g₂ n k m, g₃ n k m}

/-- The base case group H₆ acting on Fin 6 (when n = k = m = 0) -/
abbrev H₆ : Subgroup (Equiv.Perm (Fin 6)) := H 0 0 0

/-- g₁ is in H -/
theorem g₁_mem_H (n k m : ℕ) : g₁ n k m ∈ H n k m := by
  apply Subgroup.subset_closure
  simp

/-- g₂ is in H -/
theorem g₂_mem_H (n k m : ℕ) : g₂ n k m ∈ H n k m := by
  apply Subgroup.subset_closure
  simp

/-- g₃ is in H -/
theorem g₃_mem_H (n k m : ℕ) : g₃ n k m ∈ H n k m := by
  apply Subgroup.subset_closure
  simp

/-- Any element of H can be written as a product of generators and their inverses -/
theorem H_generated (n k m : ℕ) :
    H n k m = Subgroup.closure {g₁ n k m, g₂ n k m, g₃ n k m} := rfl
