/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AF-Tests Project
-/
import LemmaFeld.GroupTheory.AF.Core
import LemmaFeld.GroupTheory.AF.BaseCase.Lemma03
import Mathlib.GroupTheory.Perm.Cycle.Concrete

/-!
# Lemma 6: Commutator [g₁, g₂] Contains 3-Cycles

The commutator [g₁, g₂] = g₁⁻¹ g₂⁻¹ g₁ g₂ is a product of two disjoint 3-cycles.

## Main Results

* `commutator_g₁_g₂` - Definition of the commutator [g₁, g₂]
* `commutator_g₁_g₂_base_case_eq` - In base case: [g₁, g₂] = (0 2 4)(1 3 5)
* `commutator_g₁_g₂_has_3cycles` - The commutator contains 3-cycles

## Proof Strategy

Direct computation using `native_decide` for the base case n=k=m=0.
The commutator of two permutations that don't commute produces elements
of smaller support, yielding two disjoint 3-cycles.

## Reference

See `examples/lemmas/lemma06_commutator_g1g2.md` for the natural language proof.
-/

open Equiv Perm

/-- The commutator [g₁, g₂] = g₁⁻¹ * g₂⁻¹ * g₁ * g₂ -/
def commutator_g₁_g₂ (n k m : ℕ) : Perm (Omega n k m) :=
  (g₁ n k m)⁻¹ * (g₂ n k m)⁻¹ * (g₁ n k m) * (g₂ n k m)

-- ============================================
-- BASE CASE: n = k = m = 0 (S₆)
-- ============================================

/-- The commutator [g₁, g₂] in the base case equals (0 2 4)(1 3 5).
    In 1-indexed notation: (1 3 5)(2 4 6) - two disjoint 3-cycles. -/
theorem commutator_g₁_g₂_base_case_eq :
    commutator_g₁_g₂ 0 0 0 = c[0, 2, 4] * c[1, 3, 5] := by
  native_decide

-- ============================================
-- ELEMENT-WISE VERIFICATION
-- ============================================

/-- Commutator action on element 0: 0 → 2 -/
theorem comm_g₁_g₂_action_0 : commutator_g₁_g₂ 0 0 0 0 = 2 := by native_decide

/-- Commutator action on element 1: 1 → 3 -/
theorem comm_g₁_g₂_action_1 : commutator_g₁_g₂ 0 0 0 1 = 3 := by native_decide

/-- Commutator action on element 2: 2 → 4 -/
theorem comm_g₁_g₂_action_2 : commutator_g₁_g₂ 0 0 0 2 = 4 := by native_decide

/-- Commutator action on element 3: 3 → 5 -/
theorem comm_g₁_g₂_action_3 : commutator_g₁_g₂ 0 0 0 3 = 5 := by native_decide

/-- Commutator action on element 4: 4 → 0 -/
theorem comm_g₁_g₂_action_4 : commutator_g₁_g₂ 0 0 0 4 = 0 := by native_decide

/-- Commutator action on element 5: 5 → 1 -/
theorem comm_g₁_g₂_action_5 : commutator_g₁_g₂ 0 0 0 5 = 1 := by native_decide

/-- First 3-cycle (0 2 4) closes: 0 → 2 → 4 → 0 -/
theorem comm_first_cycle_closes :
    commutator_g₁_g₂ 0 0 0 (commutator_g₁_g₂ 0 0 0 (commutator_g₁_g₂ 0 0 0 0)) = 0 := by
  native_decide

/-- Second 3-cycle (1 3 5) closes: 1 → 3 → 5 → 1 -/
theorem comm_second_cycle_closes :
    commutator_g₁_g₂ 0 0 0 (commutator_g₁_g₂ 0 0 0 (commutator_g₁_g₂ 0 0 0 1)) = 1 := by
  native_decide

-- ============================================
-- 3-CYCLE EXTRACTION
-- ============================================

/-- The first component c[0, 2, 4] is a 3-cycle -/
def first_3cycle : Perm (Omega 0 0 0) := c[0, 2, 4]

/-- The second component c[1, 3, 5] is a 3-cycle -/
def second_3cycle : Perm (Omega 0 0 0) := c[1, 3, 5]

/-- The two 3-cycles are disjoint (their supports don't overlap) -/
theorem cycles_disjoint :
    Disjoint (first_3cycle).support (second_3cycle).support := by
  native_decide

/-- The commutator [g₁, g₂] is in H (the subgroup generated by g₁, g₂, g₃) -/
theorem commutator_g₁_g₂_mem_H : commutator_g₁_g₂ 0 0 0 ∈ H 0 0 0 := by
  unfold commutator_g₁_g₂
  apply Subgroup.mul_mem
  · apply Subgroup.mul_mem
    · apply Subgroup.mul_mem
      · exact Subgroup.inv_mem _ (g₁_mem_H 0 0 0)
      · exact Subgroup.inv_mem _ (g₂_mem_H 0 0 0)
    · exact g₁_mem_H 0 0 0
  · exact g₂_mem_H 0 0 0

-- ============================================
-- BASE CASE ANALYSIS: Individual 3-cycles NOT in H₆
-- ============================================

/-! ### Important: Base Case Structure

In the base case (n=k=m=0), H₆ ≅ S₄ with |H₆| = 24 (Lemma 3-4).
H₆ preserves the block structure B₀ = {{0,3}, {1,4}, {2,5}} (Lemma 1-3).

The individual 3-cycles c[0,2,4] and c[1,3,5] are NOT in H₆ because they
break this block structure:
- c[0,2,4] maps Block1 = {0,3} to {2,3}, which is not a block
- c[1,3,5] maps Block2 = {1,4} to {3,4}, which is not a block

The PRODUCT c[0,2,4] * c[1,3,5] = [g₁,g₂] IS in H₆, but the individual
cycles cannot be extracted in the base case.

For the general case (n+k+m ≥ 1), the Main Theorem uses a different strategy:
squaring (c₁₂ * c₁₃⁻¹)² eliminates 2-cycles and yields a single 3-cycle.
See MainTheorem.lean for the correct 3-cycle extraction. -/

/-- c[0,2,4] does NOT preserve block B₀ - it maps {0,3} to {2,3} -/
theorem first_3cycle_breaks_blocks :
    Block1.image first_3cycle ∉ B₀ := by native_decide

/-- c[1,3,5] does NOT preserve block B₀ - it maps {1,4} to {3,4} -/
theorem second_3cycle_breaks_blocks :
    Block2.image second_3cycle ∉ B₀ := by native_decide

/-- c[0,2,4] is NOT in H₆ (base case) because it breaks the block structure -/
theorem first_3cycle_not_mem_H₆ : first_3cycle ∉ H 0 0 0 := by
  intro h
  have hpres := LemmaFeld.GroupTheory.AF.BaseCase.H₆_imprimitive ⟨first_3cycle, h⟩ Block1 Block1_mem_B₀
  exact first_3cycle_breaks_blocks hpres

/-- c[1,3,5] is NOT in H₆ (base case) because it breaks the block structure -/
theorem second_3cycle_not_mem_H₆ : second_3cycle ∉ H 0 0 0 := by
  intro h
  have hpres := LemmaFeld.GroupTheory.AF.BaseCase.H₆_imprimitive ⟨second_3cycle, h⟩ Block2 Block2_mem_B₀
  exact second_3cycle_breaks_blocks hpres
